# Generated by Django 4.1.7 on 2023-03-10 20:21

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], default=dict, use_json_field=True),
            preserve_default=False,
        ),
    ]
