# Generated by Django 4.1.7 on 2023-03-10 20:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('extended_image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))], use_json_field=True),
        ),
    ]
